### ISSUE TITLE
Seria possível parametrizar Unidades Organizacionais e Grupos?

### ISSUE THREAD

**Issue by alecostaweb** [uspdev/web-ldap-admin#122]
A idea é...
Ao sincronizar, quando o usuário pertence ao grupo Aluno de Graduação, todos os usuários do grupo são criados dentro da Unidade Organizacional informada no .env.

**Comment by alecostaweb** [comment]
O pacote adldap2 pode mover o usuário para a unidade organizacional com o método:

**Comment by thiagogomesverissimo** [comment]
unidade organizacional  e grupos são coisas diferentes, não?

Você pretendem criar mais que uma unidade organizacional ?

**Comment by alecostaweb** [comment]
hehehe.... claro que são.
O que quis dizer é... sinalizar no .env que:
Todo usuário do grupo Aluno de Graduação seja criado na unidade organizacional PROALUNO
Entendeu?

Sobre criar mais de uma unidade organizacional, hoje em nosso AD existe ADECA/Users/ALUNOS/PROALUNO

Sei que o adldap2 pode mover usuários para uma OU e tbm criar novas OUs

**Comment by alecostaweb** [comment]
Algo como (no .env):

LDAP_GROUP_OU = '"Aluno de Graduação" = "PROALUNO"'

**Comment by thiagogomesverissimo** [comment]
interessante

**Comment by alecostaweb** [comment]
Vou mandar a PR por esses dias e vc avalia aí
