### ISSUE TITLE
Remover do grupo quem perdeu vínculo com respectivo grupo (verificar no replicado). Se a pessoa não estiver em nenhum grupo deve ser desativada

### ISSUE THREAD

**Issue by thiagogomesverissimo** [uspdev/web-ldap-admin#21]

**Comment by alecostaweb** [comment]
- Perdeu vínculo com a unidade, **destivar** a conta no AD, **remover dos grupos** (e adicionar ao grupo Desativados?)
- Perdeu vínculo com o grupo (tipvinext/nomabvset), mas ainda pertence a algum grupo, **remover do grupo** no AD
- Perdeu vínculo com o grupo (tipvinext/nomabvset), e não pertence a nenhum outro grupo, **destivar** a conta no AD (e adicionar ao grupo Desativados?)

**Comment by alecostaweb** [comment]
Fico na dúvida do que fazer caso alguém volte a ter vínculo, até porque que a chance é bem pequena

**Comment by alecostaweb** [comment]
Começando os testes, verifiquei o seguinte...
O comum é ao se desligar da unidade a conta fica no criada no AD, então revendo as situações:
Situações:
1) Perdeu vínculo com a unidade, remover dos grupos, adicionar ao grupo Desativados e destivar a conta. 
2) Não perdeu vínculo, mas trocou de setor, efetuar a troca de grupo.

**Comment by thiagogomesverissimo** [comment]
Exatamente isso que eu tinha pensado.
