### ISSUE TITLE
MS AD

### ISSUE THREAD

**Issue by alecostaweb** [uspdev/web-ldap-admin#41]
Para rodar com o MS AD 
Acrescentei isso no config/adldap.php
'custom_options' => [
    // See: http://php.net/ldap_set_option
    LDAP_OPT_X_TLS_REQUIRE_CERT => LDAP_OPT_X_TLS_NEVER
]

**Comment by masakik** [comment]
Também precisei disso

**Comment by thiagogomesverissimo** [comment]
Fechando, pois vi que você já inseriu no config/adldap.php e não quebrou quem usa samba.
