### ISSUE TITLE
Criar grupos com nomes baseados no tipvinext

### ISSUE THREAD

**Issue by alecostaweb** [uspdev/web-ldap-admin#51]
Se possível já criar grupos como por exemplo:
Servidores do CAC (Departamento de Artes Cênicas), onde CAC é nomabvset do setor
Docentes do CAC
Alunos de Graduação do CAC
e assim por diante

**Comment by alecostaweb** [comment]
@thiagogomesverissimo o que acha disso? 
E também da #50 ?

**Comment by thiagogomesverissimo** [comment]
As duas são ótimas =)
