### ISSUE TITLE
Email usp não cadastrado

### ISSUE THREAD

**Issue by thiagogomesverissimo** [uspdev/web-ldap-admin#86]
Para criar o usuário local o LoginController faz:

` $user->email = $userSenhaUnica->email;`

A variável  `$userSenhaUnica` é um retornado do senhaunica-socialite:

```
            'email'               => $user->email,
            'emailUsp'            => $user->emailUsp,
            'emailAlternativo'    => $user->emailAlternativo,
```

Ocorre que as vezes email está vazio! Testar emailUsp e emailAlternativo. E se ainda assim estiver vazio, dar alguma mensagem.!

**Comment by masakik** [comment]
Essa verificação é feita no senhaunica-socialite e caso não tenha email ele envia invalido+nro do codpes@usp.br
