### ISSUE TITLE
Os vínculos que deve ser sincronizados poderia vir no .env

### ISSUE THREAD

**Issue by thiagogomesverissimo** [uspdev/web-ldap-admin#88]
SYNC_VINCULOS='ALUNOGR, ALUNOPOS, ALUNOCEU, ALUNOEAD ,ALUNOPD,ALUNOCONVENIOINT,SERVIDOR ESTAGIARIORH'

**Comment by alecostaweb** [comment]
Na tela de sincronização, ldapusers/sync, isso já é seletivo inclusive utilizando o tipvinext.
Talvez ter algo como...
Documentar no .env.example todos os tipos de tipvinext disponíveis
E na variável SYNC_VINCULOS='tipvinext1, tipvinext2, tipvinext3...', pode-se deixar padrão no .env.example 'Servidor, Docente'
E na tela de sincronização só mostra disponível para sincronizar o que está em SYNC_VINCULOS
O que acha @thiagogomesverissimo?

**Comment by masakik** [comment]
e se colocar em um config que preserva a ultima seleção efetuada? Assim como os codpes não sincronizados que já ficam no config.
