### ISSUE TITLE
Ao adicionar usuario manual dá erro no replicado

### ISSUE THREAD

**Issue by masakik** [uspdev/web-ldap-admin#93]
Sendo usuário cadastrado manualmente não deveria consultar o replicado mas ele o faz para pegar a data de nascimento para cadastrar como senha. Tem também a questão da senha não atender às policies do AD (#92)

**Comment by masakik** [comment]
estou pensando na configuração e poderia colocar no .env
LDAP_DEFAULT_PASSWORD=complexo, para a complexidade habilitada.
Se não estiver setado pode deixar como está mas abre a possibilidade de outros valores.
Para o caso complexo pensei em gerar uma senha aleatória que atenda aos requisitos e posteriormente enviar por email ao usuário.
Pode ser?

**Comment by thiagogomesverissimo** [comment]
perfeito para mim

**Comment by alecostaweb** [comment]
Pode ser true ou false, sendo true (complexo), aliás deixa no .example como true por ser padrão nos ads

**Comment by masakik** [comment]
a ideia do complexo é que poderia ter a opção por exemplo de datanasc como está agora ou outro valor que alguém pode querer colocar.

**Comment by alecostaweb** [comment]
Complexidade de senha: Reparei que pela aplicação aqui estar configurada no .env com o controlador de domínio Administrator, a police de senha (8 caracteres tendo pelo menos 1 caracter especial) não é efetiva. Isso é bom porque no momento da sincronização os usuários são criaddos com senha inicial ddmmaaaa (dtanasc). Nesse sentido podemos incluir uma variável no .env.example informando a complexidade de acordo com a police do serivdor AD. Em seguida no laravel antes de trocar a senha, verificar se a senha informada atende a complexidade parametrizada.
 
Senha inicial: Vendo os comentários, podemos tentar parametrizar a senha inicial com outros campos da pessoa, ex.: cpf (nem todos tem, mas acredito que mais de 90% pode-se resolver assim), combinar dtanasc + codpes, e outras sugestões.

E-mail: Quando um admin editar a conta pode-se acrescentar a opção de enviar e-mail com a senha inicial e também ter a opção de trocar a senha ao logar.

O que acham, @thiagogomesverissimo e @masakik?
